### ISSUE TITLE
Насчёт стиля "оброботки" ошибок

### ISSUE THREAD

**Issue by ghost** [celtrecium/libsbvector#1]
Наблюдаю множество подобных функций:
```c
int
sbv_resize (sbvector_t *sbv, size_t newsize)
{
  if (sbv_resize_capacity (sbv, newsize) == EXIT_FAILURE)
    return EXIT_FAILURE;

  sbv->length = newsize;

  return EXIT_SUCCESS;
}
```
Здесь, как видно, используются константы `EXIT_FAILURE` и `EXIT_SUCCESS`, чтобы показать, успешно ли или неуспешно закончилась работа функции. Всё супер, но соглашение совершенно ненаглядное. 

Я предлагаю перейти на похоже соглашение, которое по сигнатуре функции будет чётко говорить, что возвращается:
```c
successfully
sbv_resize (sbvector_t *sbv, size_t newsize)
{
  if (sbv_resize_capacity (sbv, newsize) == bad)
    return bad;

  sbv->length = newsize;

  return okay;
}
```
Здесь `successfully` можно представить как алиас на `bool`, а `okay` и `bad` соответственно на `true` и `false`. 

Возможно, что это покажется весьма многословно, поэтому можно не делать эти алисы, а использовать ~~голые~~ `bool`, `true`, `false`. Тут, думаю, понятно. 
```c
bool
sbv_resize (sbvector_t *sbv, size_t newsize)
{
  if (sbv_resize_capacity (sbv, newsize) == false)
    return false;

  sbv->length = newsize;

  return true;
}
```
А теперь по соглашению, как принимать это:
```c
bool ok = sbv_resize(...);
if (ok) {
    ...
```

После этого сигнатура выглядит на мой взгляд немного привлекательней.  
```c
successfully sbv_resize (sbvector_t *sbv, size_t newsize);
// or
bool sbv_resize (sbvector_t *sbv, size_t newsize);
```
Есть чё доработать, поменять соглашение, но суть, надеюсь, понятна. :woozy_face:

**Comment by celtrecium** [comment]
Так точно, мой господин. Переходим на bool
